app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # # accountのurls.pyを読み込み
    # path('', include('account.urls')),
    # todoのurls.pyを読み込み
    path('', include('account.urls')),
    path('', include('todo.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

todo/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from . import api_views as record_api_views

router = routers.DefaultRouter()
router.register('todo', record_api_views.TodoViewSet)

app_name= 'todo'

urlpatterns = [
    # viewsからindexを読み込んで、nameをindexに
    path('', views.index, name='index'),
    path('<int:pk>', views.todo_detail, name='todo_detail'),
    path('create', views.todo_create, name='todo_create'),
    path('update/<int:pk>', views.todo_update, name='todo_update'),
    path('delete/<int:pk>', views.todo_delete, name='todo_delete'),
    path('api-east/', include(router.urls)),
]

todo/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.utils import timezone
import datetime

# Create your models here.

class Todo(models.Model):
  STATUS_CHOICES = [(1, '未着手'),(2, '作業中'),(3, '完   了')]

  title = models.CharField('タイトル', max_length=55)
  body = models.TextField('詳細/内容', max_length=200)
  status = models.IntegerField(choices=STATUS_CHOICES, default=1)
  deadline = models.DateTimeField('期限', default=timezone.now)
  created = models.DateTimeField('作成日時', auto_now_add=True)
  updated = models.DateTimeField('更新日時', auto_now=True)
  create_user = models.ForeignKey(get_user_model(), on_delete=CASCADE, default=1)
  
  def publish(self):
    self.update_at = timezone.now()
    self.save()
  
  def __str__(self):
      return self.title

  def deadline_flag(self):
    today = timezone.now()
    if self.deadline < today:
      return 0
    elif self.deadline <= today + datetime.timedelta(days=3):
      return 1
    else:
      return 2

todo/forms.py
from django import forms
from .models import Todo
import bootstrap_datepicker_plus as datetimepicker

class TodoForm(forms.ModelForm):

  class Meta:
    model = Todo
    fields = ('title', 'body', 'status','deadline')
    widgets = {
          'deadline': datetimepicker.DateTimePickerInput(
                format='%Y-%m-%d %H:%M',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                })
    }

todo/views.py
from django.views.generic import(
  ListView, DetailView, CreateView, UpdateView, DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect

from .models import Todo
from .forms import TodoForm

# Create your views here.

class IndexView(LoginRequiredMixin, ListView):
  template_name = 'index.html'
  model = Todo
  context_object_name = 'todos'

  def get_queryset(self):
    return Todo.objects.filter(create_user_id = self.request.user.id).filter(status__in=[1, 2]).order_by('deadline')

index = IndexView.as_view()

class TodoDetailView(LoginRequiredMixin, DetailView):

  template_name = 'todo/detail.html'
  model = Todo
  context_object_name = 'todo'

todo_detail = TodoDetailView.as_view()

class TodoCreateView(LoginRequiredMixin, CreateView):

  template_name = 'todo/create.html'
  model = Todo
  form_class = TodoForm
  success_url = reverse_lazy('todo:index')

  def form_valid(self, form):
    qryset = form.save(commit=False)
    qryset.create_user = self.request.user
    qryset.save()
    return redirect('todo:index') 

todo_create = TodoCreateView.as_view()

class TodoUpdateView(LoginRequiredMixin, UpdateView):

  template_name = 'todo/update.html'
  model = Todo
  form_class = TodoForm
  success_url = None

  def get_success_url(self):
    success_url = reverse_lazy('todo:todo_detail', kwargs={'pk':self.kwargs['pk']})
    return success_url
  

todo_update = TodoUpdateView.as_view()

class TodoDeleteView(LoginRequiredMixin, DeleteView):

  template_name = 'todo/delete.html'
  model = Todo
  success_url = reverse_lazy('todo:index')

todo_delete = TodoDeleteView.as_view()

templates/todo/create.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block main %}

<div class="container">
  <form action="" method="post">
    <div>
      <div class="todo-form">
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.title class="form-control mb-3 rounded-pill text-dark-light" placeholder="タイトル" %}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.body class="form-control mb-3 rounded text-dark-light" placeholder="詳細/内容" %}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.deadline class="form-control mb-3 rounded text-dark-light" %}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.status class="form-control mb-3 rounded text-dark-light" %}
          </div>
        </div>
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-lg bg-white text-pink shadow border-orange">作成する</button>
      </div>
    </div>
    {% csrf_token %}
  </form>
</div>
{% block extrahead %}
{{ form.media }}
{% endblock %}

{% endblock %}

templates/todo/delete.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block main %}

<section>
  <div class="container mb-5">
    <div class="text-center py-2 mb-3">
      <span class="text-center text-danger font-20 font-weight-bold">Todoを削除します、よろしいですか？</span>
    </div>
    <div class="row">
      <div class="col-11 col-lg-8 mx-auto mb-3">
        <div class="card border rounded-pill py-3 text-dark-light px-4">
          <h5 class="mb-0 font-weight-bold font-20">タイトル：{{ todo.title }}</h5>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-11 col-lg-8 mx-auto mb-3">
        <div class="card border rounded-pill py-3 text-dark-light px-4">
          <h5 class="mb-0 font-weight-bold font-20">詳細/内容：{{ todo.body|linebreaksbr }}</h5>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-6">
        <div class="text-right">
          <form action="" method="post">
            <button type="submit" class="btn bg-white shadow text-pink border-orange">削除する</a>
            {% csrf_token %}
          </form>
        </div>
      </div>
      <div class="col-6">
        <div class="text-left">
          <a href="{% url 'todo:index' %}" class="btn bg-lightgray shadow text-dark-light border-orange">戻る</a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/todo/detail.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block main %}

<section>
  <div class="container mb-5">
    <div class="row">
      <div class="col-11 col-lg-8 mx-auto mb-3">
        <div class="card border rounded-pill py-3 text-dark-light px-4">
          <h5 class="mb-0 font-weight-bold font-20">タイトル：{{ todo.title }}</h5>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-11 col-lg-8 mx-auto mb-3">
        <div class="card border rounded-pill py-3 text-dark-light px-4">
          <h5 class="mb-0 font-weight-bold font-20">詳細/内容：{{ todo.body|linebreaksbr }}</h5>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-11 col-lg-8 mx-auto mb-3">
        <div class="card border rounded-pill py-3 text-dark-light px-4">
          <span class="mb-0 font-weight-bold font-20">期限日時：{{ todo.deadline|date:'Y/m/d H:i' }}</span>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-6">
        <div class="text-right">
          <a href="{% url 'todo:todo_update' todo.pk %}" class="btn bg-white shadow text-pink border-orange">編集する</a>
        </div>
      </div>
      <div class="col-6">
        <div class="text-left">
          <a href="{% url 'todo:index' %}" class="btn bg-lightgray shadow text-dark-light border-orange">戻る</a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/todo/update.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block main %}

<div class="container">
  <form action="" method="post">
    <div>
      <div class="todo-form">
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.title class="form-control mb-3 rounded-pill text-dark-light" placeholder="タイトル" %}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.body class="form-control mb-3 rounded text-dark-light" placeholder="詳細/内容" %}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.deadline class="form-control mb-3 rounded text-dark-light" %}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-7 col-md-6 mx-auto">
            {% render_field form.status class="form-control mb-3 rounded text-dark-light" %}
          </div>
        </div>
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-lg bg-white text-pink shadow border-orange">更新する</button>
      </div>
    </div>
    {% csrf_token %}
  </form>
</div>

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% endblock %}