account/urls.py
from django.urls import path
from . import views

app_name= 'account'
urlpatterns = [
    path('signup', views.sign_up, name="signup"),
    path('signup/submit', views.signup_submit, name="signup_submit"),
    path('signup/complete/<token>', views.sign_up_complete, name="signup_complete"),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # # accountのurls.pyを読み込み
    # path('', include('account.urls')),
    # todoのurls.pyを読み込み
    path('', include('account.urls')),
    path('', include('todo.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

templates/includes/base/footer.html
<footer>
  <div class="text-center py-3">
    <span class="text-muted">2021 ryo-East all right reserved</span>
  </div>
</footer>

templates/includes/base/nav.html
{% load static %}
<nav class="text-center">
  <a class="navbar-brand text-light font-40 font-weight-bold" href="/">Mypytodo</a>
  <div class="today">
    <span class="navbar-brand py-2 text-light font-20" href="/">
      TODAY : {% now "Y" %}/{% now "n" %}/{% now "j" %}({% now "D" %})
    </span>
  </div>
  <div class="login mb-4">
    {% if user.is_authenticated %}
    <div class="login mb-4">
      <a class="btn btn-primary mr-4">ユーザ名：{{ user.get_username }}</a>
      <a class="btn btn-danger" href="{% url 'account:logout' %}">ログアウト</a>
    </div>
    {% else %}
    <a class="btn btn-success" href="{% url 'account:signup' %}">新規登録</a>
    {% endif %}
  </div>
  
</nav>