app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # # accountのurls.pyを読み込み
    # path('', include('account.urls')),
    # todoのurls.pyを読み込み
    path('', include('account.urls')),
    path('', include('todo.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

todo/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from . import api_views as record_api_views

router = routers.DefaultRouter()
router.register('todo', record_api_views.TodoViewSet)

app_name= 'todo'

urlpatterns = [
    # viewsからindexを読み込んで、nameをindexに
    path('', views.index, name='index'),
    path('<int:pk>', views.todo_detail, name='todo_detail'),
    path('create', views.todo_create, name='todo_create'),
    path('update/<int:pk>', views.todo_update, name='todo_update'),
    path('delete/<int:pk>', views.todo_delete, name='todo_delete'),
    path('api-east/', include(router.urls)),
]

todo/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.utils import timezone
import datetime

# Create your models here.

class Todo(models.Model):
  STATUS_CHOICES = [(1, '未着手'),(2, '作業中'),(3, '完   了')]

  title = models.CharField('タイトル', max_length=55)
  body = models.TextField('詳細/内容', max_length=200)
  status = models.IntegerField(choices=STATUS_CHOICES, default=1)
  deadline = models.DateTimeField('期限', default=timezone.now)
  created = models.DateTimeField('作成日時', auto_now_add=True)
  updated = models.DateTimeField('更新日時', auto_now=True)
  create_user = models.ForeignKey(get_user_model(), on_delete=CASCADE, default=1)
  
  def publish(self):
    self.update_at = timezone.now()
    self.save()
  
  def __str__(self):
      return self.title

  def deadline_flag(self):
    today = timezone.now()
    if self.deadline < today:
      return 0
    elif self.deadline <= today + datetime.timedelta(days=3):
      return 1
    else:
      return 2

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mytodo</title>
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/icofont.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/mypytodo.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://unpkg.com/moment@2.4.0/moment.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
</head>
<body>
  <main class="wrapper bg-gradation">
    {% include 'includes/base/nav.html' %}
    {% block main %}{% endblock %}
    {% include 'includes/base/footer.html' %}
  </main>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<section>
  <div class="container">
    <div class="todo">
      <div class="row">
        <div class="col-11 col-sm-9 col-md-8 col-lg-7 mx-auto">
        {% regroup todos by deadline_flag as todo_list %}
          {% for todo in todo_list %}
          <h3 class="text-white">
            {% if todo.grouper == 0 %}
              期限切れ
            {% elif todo.grouper == 1 %}
              もうすぐ期限(3日)
            {% else %}
              まだ余裕
            {% endif %}
          </h3>
          {% for todo in todo.list %}
          <div class="card rounded-pill mb-2
            {% if todo.deadline_flag == 0 %}
              border-red alert-danger
            {% elif todo.deadline_flag == 1 %}
              border-yellow alert-warning
            {% endif %}"
          >
            <div class="container py-2">
              <div class="row">
                <div class="col-10 col-md-9">
                  <div class="px-3">
                    <div class="badge 
                    {% if todo.status == 1 %}
                      badge-secondary
                    {% elif todo.status == 2 %}
                      badge-primary
                    {% elif todo.status == 3 %}
                      badge-success
                    {% endif %}
                    ">{{ todo.get_status_display }}</div>
                    <a href="{% url 'todo:todo_detail' todo.pk %}" class="todo-title">{{ todo.title }}</a><br>
                    <span>{{ todo.deadline|date:"Y/n/j(D) H:i" }}</span>
                  </div>
                </div>
                <div class="col-2 col-md-3">
                  <div class="text-right">
                    <a href="{% url 'todo:todo_delete' todo.pk %}">
                      <i class="icofont-ui-delete font-20"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endfor %}
        </div>
      </div>
      <p class="d-inline-block bg-white plus-btn shadow">
        <a href=" {% url 'todo:todo_create' %} ">
          <i class="icofont-plus plus-icon text-pink"></i>
        </a>
      </p>
    </div>
  </div>
</section>

{% endblock %}